### ISSUE TITLE
CSS page needs content

### ISSUE THREAD

**Issue by ZachDNichols** [ZachDNichols/bemidjicomputerconsoritum#29]
At the very least, the CSS page needs some background and about for CSS.

**Comment by AzirAwry** [comment]
Once I'm done with the GIS page split this week ( maybe today .... ) I'll see what I can do about that 
- Anybody else in the DC LMK if you start workin on it so we don't conflict.

**Comment by ZachDNichols** [comment]
> Once I'm done with the GIS page split this week ( maybe today .... ) I'll see what I can do about that
> 
> * Anybody else in the DC LMK if you start workin on it so we don't conflict.

I assigned Ian to this task for the week. He should have it covered.
